version: "3"
services:
  node:
    container_name: node
    build: ./
    restart: always
    ports:
      - 3000:3000
    env_file:
      - ./.env

  openssl:
    build: ./openssl
    volumes:
      - ssl-certs:/certs

  nginx:
    container_name: nginx_app
    build: ./nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ssl-certs:/certs
volumes:
  postgres-volume:
  react-volume:
  ssl-certs:
