# version: '3'

# services:
#   app:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     image: node-typescript-app
#     container_name: node-typescript-app
#     restart: always
#     ports:
#       - "3000:3000"
